[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {}

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "python"
roots = ["pyproject.toml", "requirements.txt", "setup.py"]
language-servers = [ { name = "ruff" }, { name = "pyright" } ]
formatter = { command = "ruff", args = ["format", "-"] }
auto-format = true
